version: 2.1

jobs: 
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello"

   print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "World"
  
  print_env_var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo $MY_NAME

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - print_env_var
      - print_hello
      - print_world
